### ISSUE TITLE
Nice! How about experimental results in some simulation-based scenes?

### ISSUE THREAD

**Issue by Chocolife-96** [thu-ml/RoboticsDiffusionTransformer#10]
Did you try to conduct experiments in some simulators before the embodiment cases in the paper? Did it work well in simulation-based scenes?

Currently, I do not have some real mechanical arms for experiments, so could you recommend some simultors so that I can follow your work in simultors?

Thank you very much

**Comment by csuastt** [comment]
We are developing sim env:) The control mode of sim env is not consistent with the one in our model. We need some time to fix it.
Stay tuned!
