### ISSUE TITLE
Applicability of RDT-1B on UR5 Robotic Arm and Fine-Tuning Requirements

### ISSUE THREAD

**Issue by SupritYoung** [thu-ml/RoboticsDiffusionTransformer#11]
Hi,

First, congratulations on the excellent work with RDT-1B! 🥳 Your approach to diffusion-based bimanual manipulation and the introduction of a unified action space are both impressive and inspiring.

I am interested in adapting your method for use on a different robotic setup, specifically a UR5 robotic arm. I have a few questions regarding this adaptation:

- Compatibility: Given the unified action space you've introduced, would it be feasible to apply RDT-1B on a UR5 arm setup? Are there specific adjustments or considerations you would recommend?

- Fine-Tuning Requirements: Assuming additional fine-tuning is needed for optimal performance on UR5, could you provide guidance on the approximate data volume and computational resources (e.g., GPU requirements) necessary for fine-tuning?

Any insights or recommendations would be greatly appreciated. Thank you again for your work on this exciting project! 🙏

**Comment by csuastt** [comment]
Thanks for your attention!

Compatibility: Yes, it is compatible. No adjustment is needed. You can control a UR5 with either a joint-based or EEF-based controller.
Fine-Tuning Requirements: At least 24GB VRAM.

**Comment by csuastt** [comment]
You can join our WeChat group!
https://rdt-robotics.github.io/rdt-robotics/wechat.html

**Comment by csuastt** [comment]
You can join our WeChat group!
https://rdt-robotics.github.io/rdt-robotics/wechat.html

**Comment by klein0809** [comment]
> You can join our WeChat group! https://rdt-robotics.github.io/rdt-robotics/wechat.html

Hello,群满啦 有8群吗~

**Comment by csuastt** [comment]
Here: https://rdt-robotics.github.io/rdt-robotics/wechat.html
