### ISSUE TITLE
Dataloder thread issues

### ISSUE THREAD

**Issue by budzianowski** [thu-ml/RoboticsDiffusionTransformer#12]
Thanks for awesome paper and model! I was experimenting with multi-node training and sometimes (I can't trace the problem) I end up running into:
`Error catched when processing sample from viola: The global thread pool has not been initialized.: ThreadPoolBuildError { kind: GlobalPoolAlreadyIniti alized }` issues coming from the tokenizer of the llm. Have you seen this error before? I run the producer, fill the buffer and then run the training.

I assume the producer is blocking some threads for the rust tokenizer fast of the T5.

**Comment by csuastt** [comment]
Maybe you can disable the parallelism of the tokenizer:
```python
import os
os.environ["TOKENIZERS_PARALLELISM"] = "false"
```

In any case, I would suggest you use the [HDF5VLADataset](https://github.com/thu-ml/RoboticsDiffusionTransformer/blob/main/data/hdf5_vla_dataset.py) rather than the TensorFlow Dataset. That way, you will not need any producer...
