### ISSUE TITLE
Mobile ALOHA Dataset Conversion Issues

### ISSUE THREAD

**Issue by WangZhiXiong0** [thu-ml/RoboticsDiffusionTransformer#16]
Thanks for sharing, I downloaded Mobile ALOHA Dataset from the official website, but I got the following error during the conversion process, it recognises the number of files but does not perform the conversion operation, but ends it directly. Can you help me?
![image](https://github.com/user-attachments/assets/bb44b8da-5efb-428d-b860-f7ad08ab3808)

I found out that this problem occurs because the .hdf5 file I downloaded from the official website doesn't have the instruction key in it.How do I solve this problem if I want to use this dataset?
If I want to use only this one dataset, how would the pre-training commands be adjusted

**Comment by WangZhiXiong0** [comment]
Thank you very much for your response and I will continue to look forward to follow-up instructions.

**Comment by WangZhiXiong0** [comment]
I would like to ask you one more question. I would like to use only part of the RoboSet data to verify that I can run the code successfully. Apart from removing irrelevant datasets from pretrain_datasets.json and pretrain_sample_weights.json, are there any changes that need to be made to the ‘producers’ before I start pre-training?Thank you for your reply.

**Comment by csuastt** [comment]
I am not sure whether TFDataset will raise an error if you only have part of the RoboSet files.

**Comment by grainw** [comment]
The .hdf5 file I downloaded from the official website doesn't have the instruction key in it.Have you solved this problem? @WangZhiXiong0 @csuastt

**Comment by LBG21** [comment]
We're currently re-uploading the Aloha dataset. We'll update the repo once it's done.
