### ISSUE TITLE
Preprocessed dataset

### ISSUE THREAD

**Issue by COST-97** [thu-ml/RoboticsDiffusionTransformer#17]
Hello:
Thank you very much for your outstanding work! Your work will have a profound impact on VLA research.
During the pre-training stage, the preprocessing of various data is indeed a time-consuming and labor-intensive task. Do you consider open-sourcing the preprocessed dataset? This dataset can be directly used for model training without more format and type preprocessing. This will bring more meaningful and far-reaching impact to the VLA research community. Subsequent researchers can better follow your work to conduct relevant theoretical research.

**Comment by csuastt** [comment]
We have open-sourced all the details of the preprocessing of various datasets. See [here](https://github.com/thu-ml/RoboticsDiffusionTransformer/tree/main/data/preprocess_scripts).
