### ISSUE TITLE
Would you like to create a wechat / discord group for RDT1B?

### ISSUE THREAD

**Issue by StarCycle** [thu-ml/RoboticsDiffusionTransformer#2]

**Comment by ethan-iai** [comment]
Thank you for the suggestion!  You can stay connected through the following channels:

- WeChat:
 
![WechatIMG594](https://github.com/user-attachments/assets/930ff258-3e75-4a20-b17e-d0234f7d9831)

- Discord: https://discord.gg/vsZS3zmf9A

**Comment by guangkaixu** [comment]
@ethan-iai Hi, could you please create another WeChat group? Group 3 has more than 200 members. Thank you!

**Comment by ethan-iai** [comment]
Hello,

Please find the QR codes for the RDT WeChat groups at the following link: [WeChat Groups](https://rdt-robotics.github.io/rdt-robotics/wechat.html). Currently, Groups 4 and 5 are available.

Thank you!

**Comment by shiqitannn** [comment]
can share the QR code again?

**Comment by Luo-Zhongwei** [comment]
hey,I also need it
