### ISSUE TITLE
Pretrain Dataset Question:

### ISSUE THREAD

**Issue by motor-x** [thu-ml/RoboticsDiffusionTransformer#25]
Hi,

When you used BC Z (Jang et al., 2021) as one of your pretrain dataset, did you realize that their action data is problematic？ For example:

![gripper_1](https://github.com/user-attachments/assets/9b3066ed-65d1-45fa-8699-901bdca0bd08)

The gripper action for the future 10 steps is all 0, and the state of gripper increased; However, as shown below, the gripper action for the future 10 steps is also all 0, the state of gripper decreased.

![gripper_2](https://github.com/user-attachments/assets/ec4a4b5a-a621-4871-b0ed-82872f0dc248)

Did you ever fixed this? Could you please share the fixed data? 

Thanks!

**Comment by csuastt** [comment]
In pre-training, we do not use actions. We use future states instead.

**Comment by motor-x** [comment]
Got it, thanks!

**Comment by motor-x** [comment]
Also, could you please let me know where you got the ALOHA dataset? It seems that the dataset is missing from the google drive of open-x dataset: https://console.cloud.google.com/storage/browser/gresearch/robotics?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))

Thanks!

**Comment by motor-x** [comment]
Hi,

Just one further question, I noticed that you are also using RH20T dataset. Two questions about this:

- Where to find the state and action information? I noticed that they have:
  - join.npy
  - tcp_base.npy
  but, it seems that they are all state info, right?

- They have a number of camera views, may I ask which camera views did you use for pretrain?

Thanks!

**Comment by LBG21** [comment]
We use both joint.npy and tcp_base.npy for future state prediction. To leverage the multiple camera views in RH20T, we randomly select one camera view from all views available for each data sample during training.

**Comment by motor-x** [comment]
Thank you for the quick reply! Then, what about action? Are you using future joint and tcp_base as action?

Thanks!

**Comment by LBG21** [comment]
During pre-training, we do not use action but instead future states. In the case of RH20T, the model takes current joint pose and tcp_base as proprio, and predicts future joint pose and tcp_base.

**Comment by motor-x** [comment]
Got it, I appreciate your quick and detailed response, thank you!

**Comment by motor-x** [comment]
Sorry for bothering you again! In RH20T, for the following two configs:

Cfg 1 Flexiv Dahuan AG95 OptoForce

**Comment by LBG21** [comment]
During our pre-training processing, most (I'm not sure if it's all) of the joint.npy dimensions are 6 or 7, so we simply remove all data that is not 6 or 7 dimensions.
