### ISSUE TITLE
What are the problems/challenges for this robot manipulation solution: 3D reconstruction then ROS control the arm to take the thing?

### ISSUE THREAD

**Issue by guotong1988** [thu-ml/RoboticsDiffusionTransformer#27]
thank you very much!

**Comment by csuastt** [comment]
Can you provide more details?

**Comment by guotong1988** [comment]
Just a discussion:)

**Comment by csuastt** [comment]
Hhhh! It is quite interesting. You can have a try!

**Comment by klein0809** [comment]
Hello, I have read an interesting paper. The basic idea is to reconstruct the 4D info using neuro rendering. Here is the paper "EnerVerse: Envisioning Embodied Future Space for Robotics Manipulation"
