### ISSUE TITLE
Fail to read dirty bit

### ISSUE THREAD

**Issue by wu-yutong-525** [thu-ml/RoboticsDiffusionTransformer#29]
Hi,  I try to finetune rdt-170m using Berkeley-UR5 dataset from the pretraining mixture following this [README](https://github.com/thu-ml/RoboticsDiffusionTransformer/blob/main/docs/pretrain.md). After I begin finetuning by running the `pretrain.sh`with revised parameters following the instructions, I continuously encounter the `Fail to read dirty bit` issue. Is it normal?

**Comment by JayceNing** [comment]
I met the same problem, did you solve the problem?

![image](https://github.com/user-attachments/assets/ad49d729-bb3d-41b5-b46b-fd7fe4a7df92)

**Comment by csuastt** [comment]
As in Readme, you should first run the producer. AFTER the filling is completed, run your training script...

**Comment by curryqka** [comment]
> As in Readme, you should first run the producer. AFTER the filling is completed, run your training script...

I'd like to know how to tell if the producer script is complete. Looking forward to your kindly reply.

**Comment by csuastt** [comment]
@curryqka : When the worker prints the dirty ratio, the filling-up is completed.
