### ISSUE TITLE
Can a single graphics card with 24 GB of video memory load the t5-v1_1-xxl model? Do smaller language models still exist?

### ISSUE THREAD

**Issue by qiynxx** [thu-ml/RoboticsDiffusionTransformer#3]
Can a single graphics card with 24 GB of video memory load the t5-v1_1-xxl model? Do smaller language models still exist?

**Comment by ethan-iai** [comment]
**Thank you for your question!**

Unfortunately, a single graphics card with 24 GB of VRAM is not sufficient to load the t5-v1_1-xxl model, as it requires approximately 27 GB of VRAM. However, we recommend the following approach: precompute the language embeddings on a server or web API, as outlined in [this guide](https://github.com/thu-ml/RoboticsDiffusionTransformer?tab=readme-ov-file#deployment-on-real-robots).

Smaller language models are still available but may require further alignment. You can follow the LLaVA practice, which involves training a specific adapter for your customized language model with provided pretraining dataset to integrate it into RDT.

**Please let us know if you have any further questions!**

**Comment by qiynxx** [comment]
Thanks for your answer! 
#Could you please provide the language-encoded files? We want to simply test it. @ethan-iai

**Comment by ethan-iai** [comment]
file: https://github.com/thu-ml/RoboticsDiffusionTransformer/blob/main/scripts/encode_lang.py. btw, we are currently testing t5-xxl in offload mode, which may fit in 24G GPU. keep in touch

**Comment by qiynxx** [comment]
> file: https://github.com/thu-ml/RoboticsDiffusionTransformer/blob/main/scripts/encode_lang.py. btw, we are currently testing t5-xxl in offload mode, which may fit in 24G GPU. keep in touch

Thank you very much for your reply！

**Comment by ethan-iai** [comment]
> file: [`main`/scripts/encode_lang.py](https://github.com/thu-ml/RoboticsDiffusionTransformer/blob/main/scripts/encode_lang.py). btw, we are currently testing t5-xxl in offload mode, which may fit in 24G GPU. keep in touch

It seems work. Further detail on how to toggle offload will be clarifed in https://github.com/thu-ml/RoboticsDiffusionTransformer?tab=readme-ov-file#deployment-on-real-robots

**Comment by ethan-iai** [comment]
Hi @qiynxx,

Details on encoding with offloading are thoroughly explained in the [Deployment on Real Robots](https://github.com/thu-ml/RoboticsDiffusionTransformer?tab=readme-ov-file#deployment-on-real-robots) section. Please feel free to give it a try.

Thank you for your valuable suggestion!

**Comment by pxlong** [comment]
> Hi @qiynxx,
> 
> Details on encoding with offloading are thoroughly explained in the [Deployment on Real Robots](https://github.com/thu-ml/RoboticsDiffusionTransformer?tab=readme-ov-file#deployment-on-real-robots) section. Please feel free to give it a try.
> 
> Thank you for your valuable suggestion!

Hi @ethan-iai,

First, many thanks for open-sourcing RDT.

I tried encoding with offload, but it didn't work, I got error after running `python -m scripts.encode_lang:`
```
You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
Traceback (most recent call last):
  File "/home/px/miniconda3/envs/rdt/lib/python3.10/site-packages/transformers/modeling_utils.py", line 534, in load_state_dict
    return torch.load(
  File "/home/px/miniconda3/envs/rdt/lib/python3.10/site-packages/torch/serialization.py", line 1004, in load
    overall_storage = torch.UntypedStorage.from_file(f, False, size)
RuntimeError: unable to mmap 44541587809 bytes from file <google/t5-v1_1-xxl/pytorch_model.bin>: Cannot allocate memory (12)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/px/miniconda3/envs/rdt/lib/python3.10/site-packages/transformers/modeling_utils.py", line 543, in load_state_dict
    if f.read(7) == "version":
  File "/home/px/miniconda3/envs/rdt/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/px/miniconda3/envs/rdt/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/px/miniconda3/envs/rdt/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/px/ws/my_ws/RoboticsDiffusionTransformer/scripts/encode_lang.py", line 59, in <module>
    main()
  File "/home/px/ws/my_ws/RoboticsDiffusionTransformer/scripts/encode_lang.py", line 28, in main
    text_embedder = T5Embedder(
  File "/home/px/ws/my_ws/RoboticsDiffusionTransformer/models/multimodal_encoder/t5_encoder.py", line 80, in __init__
    self.model = T5EncoderModel.from_pretrained(
  File "/home/px/miniconda3/envs/rdt/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3556, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "/home/px/miniconda3/envs/rdt/lib/python3.10/site-packages/transformers/modeling_utils.py", line 555, in load_state_dict
    raise OSError(
OSError: Unable to load weights from pytorch checkpoint file for 'google/t5-v1_1-xxl/pytorch_model.bin' at 'google/t5-v1_1-xxl/pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
```

my params in `scripts/encode_lang.py`:
```
GPU = 0
MODEL_PATH = "google/t5-v1_1-xxl"
CONFIG_PATH = "configs/base.yaml"
SAVE_DIR = "outs/"

# Modify this to your task name and instruction
TASK_NAME = "lift_cube"
INSTRUCTION = "Pick up the cube with your two arms and lift it up."

# Note: if your GPU VRAM is less than 24GB, 
# it is recommanded to enable offloading by specifying an offload directory.
OFFLOAD_DIR = "offload"  
```

**Comment by ethan-iai** [comment]
It looks like you’re facing an issue with loading the T5 model. The error is happening because the system cannot allocate enough memory for the model weights (44541587809 bytes or around 41.5 GB). This is likely because the model is too large for your available CPU memory, which is no related to offloading. Please double-check that your system (or cloud environment) has enough memory. If you’re working on a local machine, you might need to switch to run on the server.

**Comment by pxlong** [comment]
> It looks like you’re facing an issue with loading the T5 model. The error is happening because the system cannot allocate enough memory for the model weights (44541587809 bytes or around 41.5 GB). This is likely because the model is too large for your available CPU memory, which is no related to offloading. Please double-check that your system (or cloud environment) has enough memory. If you’re working on a local machine, you might need to switch to run on the server.

thanks. @ethan-iai 

i only have a local machine with 32GB memeory.

**Comment by csuastt** [comment]
My suggestions will be:
1. Try to offload to disk, you may need to google...
2. Try to encode language embeddings on a server machine with enough CPU memory.
3. Finally, if the above tips don't work, you may switch to a smaller encoder when fine-tuning.

**Comment by pxlong** [comment]
> My suggestions will be:
> 
> 1. Try to offload to disk, you may need to google...
> 2. Try to encode language embeddings on a server machine with enough CPU memory.
> 3. Finally, if the above tips don't work, you may switch to a smaller encoder when fine-tuning.

many thanks. @csuastt @ethan-iai 

I've increaed my CPU memory to 64GB, it works now.
