### ISSUE TITLE
The process of detecting dirty bits in a chunk will not stop.

### ISSUE THREAD

**Issue by liuzhenO** [thu-ml/RoboticsDiffusionTransformer#31]
Thank you for sharing your research results !
During the process of a producer filing a chunk, the detection of dirty bits within the chunk after it is filed will not stop. Is this situation something that requires intervention to terminate, or should one wait for an extended period of time?

![404e08deb89c67870d427044c186bfb](https://github.com/user-attachments/assets/945a4036-170b-4fbd-b683-0f1514448847)

**Comment by csuastt** [comment]
Once you see this, you can continue... It is normal, and bug-free lol
