### ISSUE TITLE
Do you have any simulation to recommend?

### ISSUE THREAD

**Issue by gxy-TJU** [thu-ml/RoboticsDiffusionTransformer#32]
You make a great work! I want to run it in aloha(or some dual arms), but i don't have a real robot, so i want to simulate it in any simulator, and use the public datasets in the internet or collected datasets in simulation to the format like you. But i don't know which simulation can i do it easily, because i see the issues that you mentioned that sim_env is a little difficulty，so do you have any thing to recommed? Or it is better to have a simple guidiance. 
Thank you for any response!

**Comment by csuastt** [comment]
We will realise our simulation benchmark within a week. Stay tuned!
