### ISSUE TITLE
May i ask if it  deploy on a new robot and fine-tuning it with only 1-5tracks？How is the generalization？

### ISSUE THREAD

**Issue by lanlankilkil** [thu-ml/RoboticsDiffusionTransformer#33]

**Comment by csuastt** [comment]
It won't work:( 1-5 trajectories (If I understand correctly, track means trajectory) are too few for the new robot.

**Comment by ethan-iai** [comment]
> It won't work:( 1-5 trajectories (If I understand correctly, track means trajectory) are too few for the new robot.

@lanlankilkil You can give it a shot, but it’s not likely to adapt the model to a brand new embodiment with just 1-5 trajectories. Let me know if you need more help! 😊
