### ISSUE TITLE
missing 'qpos' in bridgeV2 dataset

### ISSUE THREAD

**Issue by huangxu1991** [thu-ml/RoboticsDiffusionTransformer#35]
https://github.com/thu-ml/RoboticsDiffusionTransformer/blob/f6a57c2eaaa7b4fdb2ac7432f30ea926029b86df/data/preprocess_scripts/bridgev2.py#L131-L132

hi, it seems that KEY 'qpos' is missing.

**Comment by LBG21** [comment]
Hi, if you have followed our instructions and executed `data/bridgev2/bridgedata_raw_to_numpy.py` and `data/bridgev2/bridgedata_numpy_to_tfrecord.py` to convert the raw data into TFRecord format, the resulting `.tfrecord` files should contain `qpos`. Could you please share the error message or relevant code snippets?

**Comment by huangxu1991** [comment]
thx a lot. I'll check the procedure first.

**Comment by ethan-iai** [comment]
> thx a lot. I'll check the procedure first.

Please feel free to let me know if you have any updates. I’d be happy to assist further if needed! 😊
