### ISSUE TITLE
QKN and RMSN, which is more effective?

### ISSUE THREAD

**Issue by jshang-bdai** [thu-ml/RoboticsDiffusionTransformer#39]
Hi!

The loss curves in Figure 4(a) are very helpful and thanks for sharing them. 
Do you have the curves when 1) only QKN is applied and 2) only RMSN is applied? I'm curious which technique improves the stability more or I need both.

Thanks!

**Comment by ethan-iai** [comment]
Thank you for your kind words and thoughtful question! Generating the loss curves for QKN and RMSN applied individually would require additional experiments and computational resources, which are currently beyond the scope of our analysis. That said, it’s inspiring to explore this scientific problem, and we hope your experiments yield valuable insights.

If you have any findings or need further assistance, feel free to share—we’d be happy to help where possible.
