### ISSUE TITLE
CUDA OUT OF MEMORY after several samples training

### ISSUE THREAD

**Issue by curryqka** [thu-ml/RoboticsDiffusionTransformer#43]
I want to know the setting of finetuning scripts and the related GPU memory demand.
`12/12/2024 07:07:23 - INFO - __main__ - ***** Running training *****
12/12/2024 07:07:23 - INFO - __main__ -   Num examples = 262144
12/12/2024 07:07:23 - INFO - __main__ -   Num batches each epoch = 262144
12/12/2024 07:07:23 - INFO - __main__ -   Num Epochs = 1
12/12/2024 07:07:23 - INFO - __main__ -   Instantaneous batch size per device = 1
12/12/2024 07:07:23 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 1
12/12/2024 07:07:23 - INFO - __main__ -   Gradient Accumulation steps = 1
12/12/2024 07:07:23 - INFO - __main__ -   Total optimization steps = 200000
Steps:   0%|                                                                                                                                                              | 0/200000 [00:00<?, ?it/s][2024-12-12 07:07:27,434] [INFO] [loss_scaler.py:183:update_scale] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 4294967296, reducing to 2147483648
Steps:   0%|                                                                                                                         | 1/200000 [00:04<228:23:10,  4.11s/it, loss=0.00152, lr=0.0001][2024-12-12 07:07:27,845] [INFO] [loss_scaler.py:183:update_scale] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 2147483648, reducing to 1073741824
Steps:   0%|                                                                                                                        | 2/200000 [00:04<106:29:07,  1.92s/it, loss=0.000271, lr=0.0001][2024-12-12 07:07:28,214] [INFO] [loss_scaler.py:183:update_scale] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 1073741824, reducing to 536870912
Steps:   0%|                                                                                                                         | 3/200000 [00:04<67:12:21,  1.21s/it, loss=0.000405, lr=0.0001][2024-12-12 07:07:28,573] [INFO] [loss_scaler.py:183:update_scale] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 536870912, reducing to 268435456
Steps:   0%|                                                                                                                         | 4/200000 [00:05<48:30:42,  1.15it/s, loss=0.000553, lr=0.0001][2024-12-12 07:07:28,943] [INFO] [loss_scaler.py:183:update_scale] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 268435456, reducing to 134217728
Steps:   0%|                                                                                                                         | 5/200000 [00:05<38:27:53,  1.44it/s, loss=0.000105, lr=0.0001][2024-12-12 07:07:29,322] [INFO] [loss_scaler.py:183:update_scale] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 134217728, reducing to 67108864
Steps:   0%|                                                                                                                         | 6/200000 [00:05<32:33:21,  1.71it/s, loss=0.000135, lr=0.0001][2024-12-12 07:07:29,701] [INFO] [loss_scaler.py:183:update_scale] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 67108864, reducing to 33554432
Steps:   0%|                                                                                                                          | 7/200000 [00:06<29:05:59,  1.91it/s, loss=9.82e-5, lr=0.0001][2024-12-12 07:07:30,084] [INFO] [loss_scaler.py:183:update_scale] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 33554432, reducing to 16777216
Steps:   0%|                                                                                                                         | 8/200000 [00:06<26:15:27,  2.12it/s, loss=0.000243, lr=0.0001][2024-12-12 07:07:30,441] [INFO] [loss_scaler.py:183:update_scale] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 16777216, reducing to 8388608
Steps:   0%|                                                                                                                          | 9/200000 [00:07<24:24:19,  2.28it/s, loss=0.00089, lr=0.0001][2024-12-12 07:07:30,845] [INFO] [loss_scaler.py:183:update_scale] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 8388608, reducing to 4194304
Steps:   0%|                                                                                                                        | 10/200000 [00:07<23:40:37,  2.35it/s, loss=0.000155, lr=0.0001][2024-12-12 07:07:31,195] [INFO] [loss_scaler.py:183:update_scale] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 4194304, reducing to 2097152
Steps:   0%|                                                                                                                        | 11/200000 [00:07<22:22:06,  2.48it/s, loss=0.000348, lr=0.0001][2024-12-12 07:07:31,548] [INFO] [loss_scaler.py:183:update_scale] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 2097152, reducing to 1048576
Steps:   0%|                                                                                                                        | 12/200000 [00:08<21:31:54,  2.58it/s, loss=0.000687, lr=0.0001][2024-12-12 07:07:31,896] [INFO] [loss_scaler.py:183:update_scale] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 1048576, reducing to 524288
Steps:   0%|                                                                                                                         | 13/200000 [00:08<21:11:03,  2.62it/s, loss=3.14e-5, lr=0.0001][2024-12-12 07:07:32,258] [INFO] [loss_scaler.py:183:update_scale] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 524288, reducing to 262144
Steps:   0%|                                                                                                                          | 14/200000 [00:08<20:29:55,  2.71it/s, loss=3.3e-5, lr=0.0001][2024-12-12 07:07:32,600] [INFO] [loss_scaler.py:183:update_scale] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 262144, reducing to 131072
Steps:   0%|                                                                                                                        | 15/200000 [00:09<20:02:00,  2.77it/s, loss=0.000253, lr=0.0001][2024-12-12 07:07:32,941] [INFO] [loss_scaler.py:183:update_scale] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 131072, reducing to 65536
Steps:   0%|                                                                                                                        | 16/200000 [00:09<19:48:29,  2.80it/s, loss=0.000143, lr=0.0001][2024-12-12 07:07:33,319] [INFO] [loss_scaler.py:183:update_scale] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 65536, reducing to 32768
Steps:   0%|                                                                                                                        | 17/200000 [00:09<20:04:52,  2.77it/s, loss=0.000617, lr=0.0001]Traceback (most recent call last):
`
CUDA OUT OF MEMORY happened！torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 4.58 GiB. GPU 0 has a total capacty of 39.39 GiB of which 72.00 MiB is free. Process 2575157 has 39.31 GiB memory in use. Of the allocated memory 34.88 GiB is allocated by PyTorch, and 3.77 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF。

`train_batch_size=1,sample_batch_size=2`，setting dtype=fp16

**Comment by XuMengyaAmy** [comment]
me too, help!

**Comment by curryqka** [comment]
> me too, help!

This problem can be lightened through offloading some parameters to the CPU.
`{
    "bf16": {
        "enabled": "auto"
    },
    "train_micro_batch_size_per_gpu": "auto",
    "train_batch_size": "auto",
    "gradient_accumulation_steps": "auto",
    "zero_optimization": {
        "stage": 2,
        "overlap_comm": true,
        "contiguous_gradients": true,
        "sub_group_size": 1e9,
        "offload_optimizer": {
            "device": "cpu",
            "pin_memory": true
        }
    }
}`

**Comment by curryqka** [comment]
> Based on the log you’ve provided, I have a few suggestions to help resolve the issue:
> 
> 1. Please refer to the [VRAM reduction section in the FAQ](https://github.com/thu-ml/RoboticsDiffusionTransformer?tab=readme-ov-file#1-how-can-i-fine-tune-rdts-with-limited-vram) for tips on how to manage GPU memory more efficiently during training.
> 2. The OVERFLOW warning is a bit unusual, and it could be related to the use of `dtype=fp16`. I recommend switching to `bf16` as it can help avoid numerical instability issues. If the problem persists even after switching to `bf16`, I would suggest performing a more detailed numerical analysis of the model’s training process to ensure optimal results.
> 
> Let me know if this helps or if you need further assistance!

To begin with, the default data type bf16 was used. Unfortunately, my machine does not have cutless installed, which lead to failure when used bf16 as the data type of tensors.
