### ISSUE TITLE
Changing chunk size, requires re-training?

### ISSUE THREAD

**Issue by Wonder1905** [thu-ml/RoboticsDiffusionTransformer#45]
Hi, I desire in changing the "action_chunk_size" do you think it may require a massive re-training?

Thanks!

**Comment by ethan-iai** [comment]
The weights, except for `x_pos_embed`, can be loaded as usual. Changing the action_chunk_size may require a bit more training than usual, but it shouldn’t necessitate a full retraining. However, it’s recommended to fine-tune the model for a bit longer with the new configuration to ensure the best possible performance.
