### ISSUE TITLE
Deployment on Real-Robots

### ISSUE THREAD

**Issue by becauseofAI** [thu-ml/RoboticsDiffusionTransformer#51]
How to deploy RDT models to control real robotic arms, such as Mobile Aloha?
Can anyone provide guidance on hardware connection, software interface, model running, etc.?
Any help will contribute to the progress of the community.

**Comment by ethan-iai** [comment]
Thank you for your inquiry! The hardware for robotic arms, including Mobile Aloha, is quite diverse, and the connections, APIs, and control methods can vary significantly depending on the specific implementation. Even within the Mobile Aloha category, there are different types of setups with varying configurations.

As such, deploying RDT models to control real robotic arms may require specific adjustments based on the hardware you are using. Unfortunately, instance-level hardware details often go beyond the scope of our research, but I would recommend reaching out to your hardware suppliers for more specific advice on hardware connections, or consulting the specific hardware documentation for setup instructions.
